[window]
opacity = 0.95
dynamic_title = true
dynamic_padding = true
padding = { x = 2 }
blur = true
resize_increments = true
dimensions = { columns = 90, lines = 25 }

[env]
TERM = "xterm-256color"


[font]
normal = { family = "Hack Nerd Font" }
size = 11.3


[cursor]
style.shape = "Beam"
style.blinking = "On"
thickness = 0.15

[mouse]
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]

[colors]
primary = { background = "#171421", foreground = "#D0CFCC" }

# [colors.cursor]
# text = "#2E3436"
# cursor = "#D3D7CF" # [colors.primary]
#
[colors.normal]
black = "#2E3436"
red = "#CC0000"
green = "#4E9A06"
yellow = "#C4A000"
blue = "#12488B"
magenta = "#75507B"
cyan = "#06989A"
white = "#D3D7CF"

[colors.bright]
black = "#555753"
red = "#EF2929"
green = "#8AE234"
yellow = "#FCE94F"
blue = "#729FCF"
magenta = "#AD7FA8"
cyan = "#34E2E2"
white = "#EEEEEC"

[colors.selection]
text = "#2E3436"
background = "#F3F4F5"

[colors.line_indicator]
background = "#4A90E2"
foreground = "#4A90E2"

[bell]
animation = "Ease"
duration = 5
color = "#ffaa00"

[terminal]


[terminal.shell]
program = "/usr/bin/zsh"
