# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
  export PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ]; then
  export PATH="$HOME/.local/bin:$PATH"
fi


# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ]; then
  export PATH="$HOME/.bin:$PATH"
fi


# source cargo
if [ -d "$HOME/.cargo/" ]; then
  . "$HOME/.cargo/env"
fi


  # Added by Toolbox App
if [ -d "$HOME/.local/share/JetBrains/Toolbox/scripts" ]; then
  export PATH="$HOME/.local/share/JetBrains/Toolbox/scripts:$PATH"
fi
if [ -d "$HOME/.deno" ]; then
	. "$HOME/.deno/env"
fi
